import{a as c,i as u}from"./assets/vendor-474f6730.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function f(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=f(t);fetch(t.href,o)}})();c.defaults.headers.common["x-api-key"]="live_u3yEvYAxGPL6AUaoQgzmpefMY5Xt0C5cztwzIhJ5Bkgdn8atxyREoXu89TrCC4ua";function m(){return c.get("https://api.thecatapi.com/v1/breeds")}function p(e){const r=new URLSearchParams({breed_ids:e});return c.get(`https://api.thecatapi.com/v1/images/search?${r}`)}const n={breedsList:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),catInfo:document.querySelector("div.cat-info")};L();n.breedsList.addEventListener("change",h);function h(e){g(e.target.value)}function g(e){d(),n.catInfo.innerHTML="",p(e).then(({data:[r]})=>{n.catInfo.innerHTML=y(r),i()}).catch(r=>{i(),l(r)})}function L(){d(),m().then(({data:e})=>{n.breedsList.innerHTML=e.map(r=>`<option value="${r.id}">${r.name}</option>`).join(""),i(),n.breedsList.classList.remove("hidden")}).catch(e=>{i(),l(e)})}function y(e){return`<div class="cat-info-card flex mt-5 pr-2 lg:pr-20">
            <img class="cat-info-image relevant w-1/3 object-cover pr-10" src="${e.url}" alt="cat" />
            <div class="cat-info-holder flex flex-col px-2.5">
              <h2 class="cat-info-title mb-2.5 text-2xl font-bold">${e.breeds[0].name}</h2>
              <p class="cat-info-text my-2.5 text-lg">${e.breeds[0].description}</p>
              <p class="cat-info-text my-2.5 text-lg"><b>Temperament:</b> ${e.breeds[0].temperament}</p>
            </div>
          </div>`}function d(){n.loader.classList.remove("hidden")}function i(){n.loader.classList.add("hidden")}function l(e){u.show({color:"red",title:"Ooops! An error occured",message:`${e.name}: ${e.message}`,position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
