import{a as c}from"./assets/vendor-aade7e8e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function f(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=f(t);fetch(t.href,o)}})();c.defaults.headers.common["x-api-key"]="live_u3yEvYAxGPL6AUaoQgzmpefMY5Xt0C5cztwzIhJ5Bkgdn8atxyREoXu89TrCC4ua";function u(){return c.get("https://api.thecatapi.com/v1/breeds")}function p(e){const r=new URLSearchParams({breed_ids:e});return c.get(`https://api.thecatapi.com/v1/images/search?${r}`)}const n={breedsList:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),catInfo:document.querySelector("div.cat-info")};L();n.breedsList.addEventListener("change",m);function m(e){h(e.target.value)}function h(e){d(),n.catInfo.innerHTML="",p(e).then(({data:[r]})=>{n.catInfo.innerHTML=g(r),s(),n.breedsList.classList.remove("hidden")}).catch(r=>{s(),l()})}function L(){d(),u().then(({data:e})=>{n.breedsList.innerHTML=e.map(r=>`<option value="${r.id}">${r.name}</option>`).join(""),s(),n.breedsList.classList.remove("hidden")}).catch(e=>{s(),l()})}function g(e){return`<div class="cat-info-card flex mt-5 pr-2 lg:pr-20">
            <img class="cat-info-image relevant w-1/3 object-cover pr-10" src="${e.url}" alt="cat" />
            <div class="cat-info-holder flex flex-col px-2.5">
              <h2 class="cat-info-title mb-2.5 text-2xl font-bold">${e.breeds[0].name}</h2>
              <p class="cat-info-text my-2.5 text-lg">${e.breeds[0].description}</p>
              <p class="cat-info-text my-2.5 text-lg"><b>Temperament:</b> ${e.breeds[0].temperament}</p>
            </div>
          </div>`}function d(){n.loader.classList.remove("hidden"),n.breedsList.classList.add("hidden")}function s(){n.loader.classList.add("hidden")}function l(e){n.catInfo.innerHTML='<p class="text-red-500 text-center text-3xl pt-40">Oops! We did not find the cat you requested 😢</p>',n.breedsList.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
